
#Docker registry configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
  namespace: kokoaly-docker-registry
  labels:
    app: registry
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: redis
      s3:
        region: {{ .Values.dockerregistry.awsregion }}
        bucket: kokoaly-docker-registry
      delete:
        enabled: true
    redis:
      addr: redis-main:6379
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

