apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: docker-registry
  namespace: kokoaly-docker-registry
spec:
  backendType: systemManager
  region: {{ .Values.dockerregistry.awsregion }}
  data:
    - key: {{ .Values.dockerregistry.ssmparameterhtpasswd }}
      name: docker-registry-htpasswd