# Redis volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redisdata
  namespace: kokoaly-docker-registry
  labels:
    app: redis
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi 
---
# Docker registry volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pv
  namespace: kokoaly-docker-registry
  labels:
    app: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dockerregistry.storage }}